module.exports = {
  english: {
    bursting: ['bursting','breaking','erupting','exploding',],
    shove: ['shove','cram','hustle','jab','poke','thrust','boost','bulldoze','elbow','jam'],
    fog: ['fog','cloud','smoke','gloom','steam','haze','nebula','murkiness'],
    humbleness: ['humbleness','bashfulness','humility','purity','prudery','innocence','modesty'],
    empty: ['empty','bare','blank','deserted','desolate','hollow','abandoned','vacant','unoccupied','unfilled','depleted','despoiled'],
    streets: ['streets','avenues','boulevards','highways','roadways','tracks','trails','thoroughfare','lanes'],
    sexy: ['sexy','hot','inviting','mature','racy','seductive','sensual','arousing','kissable','steamy','voluptuous','spicy','arousing'],
    remember: ['remembered','evoke','memorized','recall','recollect','had on my mind'],
    lost: ['lost','absent','disorientated','hidden','invisible','vanished','disappeared','invisible','gone','lacking','cast away','down the drain','misplaced','gone astray','wayward'],
    scenery: ['scenery','backdrop','landscape','spectacle','terrain','stage','mise en scène'],
    flaming: ['glowing','flaming','florid','gleaming','luminous','vibrant','vivid','beaming','flushing','aglow','lustrous'],
    glowing: ['glowing','flaming','florid','gleaming','luminous','vibrant','vivid','beaming','flushing','aglow','lustrous'],
    heart: ['heart','affection','compassion','feeling','character'],
    world: ['nature','universe','cosmos','heavenly body','sphere'],
    confused: ['baffled','bewildered','perplexed','flustered','abashed','punch-drunk'],
    shouts: ['shouts','cheers','howls','roars','barks','yells','bawls','yammers'],
    loudly: ['loudly','aloud','powerfully','ostentaciously','vociferously','shrilly','vulgarly','crashingly','thunderingly'],
    dance: ['dance','tango','waltz','boogie','rock','shimmy','rhumba','whirl','hoof it','twist','sway','promenade'],
    begin: ['begin','initiate','trigger','inaugurate','establish','set up','generate'],
    tenderness: ['tenderness','affection','goodness','lovingness','compassion','kindness','harmony'],
    unite: ['unite','band together','unify','hang together','become one','commingle','intertwine','fuse'],
    shadow: ['shadow','gloom','shade','obscurity','dusk','dimness','shelter'],
    askew: ['askew','buckled','knotted','twisted','zigzag','catawampus','slanted','topsy-turvey'],
    lust: ['lust','excitement','craving','thirst','longing','libido','sensuality','eroticism','salaciusness'],
    overwhelming: ['Overwhelming','Breathtaking','Amazing','Mind-blowing','Stunning','Shattering','Crushing','Devastating'],
    pull: ['drag','haul','pull','dislocate','remove','yank','tow','schlepp','jerk','wrench'],
    wild: ['wild','barbarian','lush','savage','free','unbroken','rude','uncivilized','vicious','primitive'],
    horny: ['oversexed','horny','hot to trot','randy','lustful','passionate','desiring'],
    temperature: ['Cold','Hot','Steamy','Boiling','Flaming','Humid','Sizzling'],
    month: ['January','February','March','April','May','June','July','August','October','November','December',],
    weatherphaenomena: ['storm','thunderstorm','blizzard','hurricane','snowstorm','whirlwind',],
    color: ['Amber','Azure','Violet','Coral','Cornflower blue','Golden','Deep pink','Spring Green','Rosy brown'],
    landscape: ['desert','hillside','mountain valley','mountain top','ridge', 'mountain range','canyon','glacier','lava dome'],
    emotion: ['anger','fear','fury','irritation','love','satisfaction','hope','pride','satisfaction'],
    animal: ['African Clawed Frog','Gentoo Penguin','Purple Emperor','Striped Rocket Frog','Cavalier King Charles Spaniel','Giant African Landsnail','Sea Urchin','Water Buffalo','Bottle Nosed Dolphin','Eastern Lowland Gorilla', 'Glow Worm','Wolly Mammoth',],
    capital: ['Paris','London','Berlin','New York','Barcelona','Lisbon','Stockholm'],
    tree: ['Oak','Pine','Dragon Blood Tree','Jabuticaba','Boojum tree'],
    spirit: ['spirit','character','enthusiasm','vigor','warmth','vitality','dauntlessness'],
    bird: ['Lazy Cisticola','Siamese Fireback','Sandy Gallito','Greater Pewee','Invisible Rail','Oleaginous Hemispingus'],
    total: ['total','absolute','wholehearted','flat out','full blast'],
    depression: ['depression','dejection','dullness','gloominess','lugubriosety','bummer'],
    water: ['water','sea','lake of tears'],
    sky: ['sky', 'heavens', 'firmament', 'empyrean',],
    meet: ['gather','flock','assemble','rendezvous','foregather','congregate'],
    soul: ['soul','animus','conscience','essence','marrow','bosom',],
    rise: ['rise','ascent','upsurge','upswing','swell',],
    clean: ['clean','graceful','pure','sparkling','unpolluted','untarnished'],
    dark: ['drab','lightless','opaque','aphotic'],
    season: ['spring','summer','winter','fall',],
    walk: ['walk','parade','stroll','promenade','stride','pace',],
    sunshine: ['sunshine','light of day','diurnal course','brightest star'],
    shine: ['shine','glitz','glaze','sparkle','shimmer','gleam',],
    sun: ['sun','flare','sol',],
    dreams: ['fantasies','imaginations','hallucinations','pipe dreams','bubbles','dreams',],
    wait: ['Wait','Hold on','Relax','But await',],
    marvelous: ['marvelous','astonishing','awe-inspiring','miraculous','phenomenal','spectacular','fabulous',],
    scene: ['scene','display','setting','exhibition','scenery','picture','stage',],
    tell: ['disclose', 'express','divulge','proclaim','call upon','summon','say'],
    dive: ['dive','plunge','leap','belly flop','nosedive',],
    stormy: ['stormy','turbulent','howling','tempestuous','torrid','raging','savage',],
    sea: ['sea','ocean','pond','surf','swell',],
    cruelness: ['cruelness','barbarity','ferment','fury','viciousness','wildness',],
    gate: ['gate','doorway','passage','port','opening',],
    salvation: ['salvation','liberation','lifeline','reprieve','escape',],
    magical: ['magical','enchanted','miraculous','mysterious','otherworldly','claivoyant','entrancing',],
    place: ['site','place','field','hangout','vicinity','habitat','venue',],
    celebrate1: ['celebrate','proclaim','carouse','rejoice','drink to','let loose','glorify',],
    celebrate2: ['jubilate','hallow','perform','praise','consecrate',],
    emotional: ['poignant','hot-blooded','tear-jerking','tender','zealous',],
    feast: ['festival','gala','clambake','potlatch','fete','carnival',],
    unification: ['unification','amalgamation','coalescence','interlocking','melding','coupling',],
    flowers: ['flowers','blossom','perennial','bud',],
    candles: ['candles','torches','rushlights','flambeaus',],
    waiting: ['waiting','watching','holding back','look forward to', 'sitting tight','anticipating',],
    glorious: ['glorious','magnificent','dazzling','heroic','triumphant','majestic',],
    explosion: ['explosion','blast','burst','detonation','fulmination',],
    whispering: ['murmuring','buzzing','whispering','humming',],
    heaven: ['heaven','nirvana','dreamland','fairyland','wonderland','happy hunting ground','Shangri-la',],
    burning: ['burning','scorching','ignited','aflame','alight',],
    princess: ['Queen','Sovereign','Princess',],
  },
}
