module.exports = {
  english: {
    bursting: ['bursting','breaking','erupting','exploding',],
    shove: ['shove','cram','hustle','jab','poke','thrust','boost','bulldoze','elbow','jam'],
    fog: ['fog','cloud','smoke','gloom','steam','haze','nebula','murkiness'],
    humbleness: ['humbleness','bashfulness','humility','purity','prudery','innocence','modesty'],
    empty: ['empty','bare','blank','deserted','desolate','hollow','abandoned','vacant','unoccupied','unfilled','depleted','despoiled'],
    streets: ['streets','avenues','boulevards','highways','roadways','tracks','trails','thoroughfare','lanes'],
    sexy: ['sexy','hot','inviting','mature','racy','seductive','sensual','arousing','kissable','steamy','voluptuous','spicy','arousing'],
    remember: ['remembered','evoke','memorized','recall','recollect','had on my mind'],
    lost: ['lost','absent','disorientated','hidden','invisible','vanished','disappeared','invisible','gone','lacking','cast away','down the drain','misplaced','gone astray','wayward'],
    scenery: ['scenery','backdrop','landscape','spectacle','terrain','stage','mise en scène'],
    flaming: ['glowing','flaming','florid','gleaming','luminous','vibrant','vivid','beaming','flushing','aglow','lustrous'],
    glowing: ['glowing','flaming','florid','gleaming','luminous','vibrant','vivid','beaming','flushing','aglow','lustrous'],
    heart: ['heart','affection','compassion','feeling','character'],
    world: ['nature','universe','cosmos','heavenly body','sphere'],
    confused: ['baffled','bewildered','perplexed','flustered','abashed','punch-drunk'],
    shout: ['shouts','cheers','howls','roars','barks','yells','bawls','yammers'],
    loudly: ['loudly','aloud','powerfully','ostentaciously','vociferously','shrilly','vulgarly','crashingly','thunderingly'],
    dance: ['dance','tango','waltz','boogie','rock','shimmy','rhumba','whirl','hoof it','twist','sway','promenade'],
    begin: ['begin','initiate','trigger','inaugurate','establish','set up','generate'],
    tenderness: ['tenderness','affection','goodness','lovingness','compassion','kindness','harmony'],
    unite: ['unite','band together','unify','hang together','become one','commingle','intertwine','fuse'],
    shadow: ['shadow','gloom','shade','obscurity','dusk','dimness','shelter'],
    askew: ['askew','buckled','knotted','twisted','zigzag','catawampus','slanted','topsy-turvey'],
    lust: ['lust','excitement','craving','thirst','longing','libido','sensuality','eroticism','salaciusness'],
    overwhelming: ['Overwhelming','Breathtaking','Amazing','Mind-blowing','Stunning','Shattering','Crushing','Devastating'],
    pull: ['drag','haul','pull','dislocate','remove','yank','tow','schlepp','jerk','wrench'],
    wild: ['wild','barbarian','lush','savage','free','unbroken','rude','uncivilized','vicious','primitive'],
    horny: ['oversexed','horny','hot to trot','randy','lustful','passionate','desiring'],
    temperature: ['Cold','Hot','Steamy','Boiling','Flaming','Humid','Sizzling'],
    month: ['January','February','March','April','May','June','July','August','October','November','December',],
    weatherphaenomena: ['storm','thunderstorm','blizzard','hurricane','snowstorm','whirlwind',],
    color: ['Amber','Azure','Violet','Coral','Cornflower blue','Golden','Deep pink','Spring green','Rosy brown'],
    landscape: ['desert','hillside','mountain valley','mountain top','ridge', 'mountain range','canyon','glacier','lava dome'],
    emotion: ['anger','fear','fury','irritation','love','satisfaction','hope','pride','satisfaction'],
    animal1: ['African Clawed Frog','Gentoo Penguin','Purple Emperor','Striped Rocket Frog'],
    animal2: ['Cavalier King Charles Spaniel','Giant African Landsnail','Sea Urchin','Water Buffalo'],
    animal3: ['Bottle Nosed Dolphin','Eastern Lowland Gorilla', 'Glow Worm','Wolly Mammoth'],
    flower: ['bergamot','amaryllus','edelweiß','foxglove','hibiscus','jasmine','lotus flowers','peach blossom'],
    capital: ['Paris','London','Berlin','New York','Barcelona','Lisbon','Stockholm'],
    tree: ['Oak','Pine','Dragon Blood Tree','Jabuticaba','Boojum tree'],
  },
}
